kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: node:lts-alpine
  commands:
  - npm install
  - hexo generate

- name: publish
  image: appleboy/drone-scp
  settings:
    target: /var/www/blog.mona.moe
    source: ./public
    host: 
      from_secret: ssh_host
    port: 22
    username: 
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    rm: true
  
trigger:
  event:
  - push
